---
- hosts: arista
  # connection: local
  gather_facts: false
  tasks:
    - name: convert to layer3 routed port
      eos_config:
         lines:
           - no switchport
           - ip routing
         parents: "{{ item }}"
      with_items:
        - interface Ethernet1
        - interface Ethernet2
        - interface Ethernet3
        - interface Ethernet4
        - interface Ethernet5

    - name: Merge interfaces Ethernet 1 and 2
      eos_lag_interfaces:
        config:
          - name: Port-Channel1
            members:
              - member: Ethernet1
                mode: active
              - member: Ethernet2
                mode: active
        state: replaced

    - name: IP address
      eos_l3_interfaces:
        config:
          - ipv4:
              - address: 192.168.13.1/24
            name: Ethernet3
          - ipv4:
              - address: 192.168.14.1/24
            name: Ethernet4
          - ipv4:
              - address: 150.1.150.1/24
            name: Ethernet5
          - ipv4:
              - address: 192.168.12.1/24
            name: Port-Channel1
          - ipv4:
              - address: 1.1.1.1/24
            name: Loopback0
        state: replaced
   
    - name: Configure BGP 65535
      eos_bgp:
        config:
          bgp_as: 65535
          router_id: 1.1.1.1
          neighbors:
            - neighbor: 150.1.150.1
              remote_as: 150
              description: EBGP_PEER_ISP
          networks:
            - prefix: 1.1.1.1
              masklen: 32
        operation: replace
    
    - name: OSPF configuration
      eos_config:
        lines:
          - router-id 1.1.1.1
          - passive-interface Ethernet5
          - network 1.1.1.1/32 area 0.0.0.0
          - network 150.1.150.2/32 area 0.0.0.0
          - network 192.168.12.1/32 area 0.0.0.0
          - network 192.168.13.1/32 area 0.0.0.0
          - network 192.168.14.1/32 area 0.0.0.0
        parents: router ospf 1
    
    - name: Bring up the interfaces
      eos_interfaces:
        config:
          - name: Ethernet1
            enabled: yes
            description: PORT-CHANNEL INTERFACE TO ARISTA-SW2
          - name: Ethernet2
            enabled: yes
            description: PORT-CHANNEL INTERFACE TO ARISTA-SW2
          - name: Ethernet3
            enabled: yes
            description: INTERFACE TO CUMULUS-SW1
          - name: Ethernet4
            enabled: yes
            description: INTERFACE TO CUMULUS-SW2
          - name: Ethernet5
            enabled: yes
            description: INTERFACE TO ISP
          - name: Port-Channel1
            enabled: yes
            description: PORT-CHANNEL INTERFACE TO ARISTA-SW2
          - name: loopback0
            enabled: yes
            description: LOOPBACK INTERFACE
          - name: Management1
            enabled: yes
            description: MANAGEMENT INTERFACE
