---
- hosts: cumulus
  # connection: local
  gather_facts: false
  tasks:
    - name: loopback inteface and address
      nclu:
        commands:
          - add loopback lo ip address 3.3.3.3/32

    - name: Add swp1 and swp 2 IP addresses
      nclu:
        commands:
          - add interface swp1 ip address 192.168.13.3/24
          - add interface swp1 alias LINK_TO_ARISTA_SW1
          - add interface swp2 ip address 192.168.23.3/24
          - add interface swp2 alias LINK_TO_ARISTA_SW2
          
    - name: Configure bridge access for vlan 100
      nclu:
        commands:
          - add interface swp3 bridge access 100
          - add interface swp3 alias LINK_HOST_ACCESS_PORT_1
          - add interface swp4 bridge access 100
          - add interface swp4 alias LINK_HOST_ACCESS_PORT_2

    - name: Configure bridge inteface and SVI inteface
      nclu:
        commands:
          - add bridge bridge ports swp3-4
          - add bridge bridge vids 100
          - add vlan 100 ip address 192.169.100.1/24
          
    - name: Quagga routing
      lineinfile:
        path: /etc/frr/daemons
        regexp: "^zebra="
        line: "zebra=yes"
        
    - name: Enable OSPF DEAMON
      lineinfile:
        path: /etc/frr/daemons
        regexp: "^ospfd="
        line: "ospfd=yes"

    - name: Enable OSPF6 DEAMON
      lineinfile:
        path: /etc/frr/daemons
        regexp: "^ospf6d="
        line: "ospf6d=yes"
        
    - name: START FRR SERVICE
      systemd:
        name: frr.service
        state: started
        enabled: yes

          
    - name: Enable OSPF
      nclu:
        commands:
          - add ospf router-id 3.3.3.3
          - add ospf passive-interface swp3
          - add ospf passive-interface swp4
          - add ospf network {{ item.prefix }} area {{ item.area }}
        description: "ENABLE OSPF"
      loop:
        - { prefix: 3.3.3.3/32, area: 0.0.0.0 }
        - { prefix: 192.168.100.0/24, area: 0.0.0.0 }
        - { prefix: 192.168.23.0/24, area: 0.0.0.0 }
        - { prefix: 192.168.13.0/24, area: 0.0.0.0 }

    - name: show results and commit
      nclu:
        commands:
          - pending
          - commit
