---
- hosts: arista
  # connection: local
  gather_facts: false
  tasks:
    - name: IP address
      eos_l3_interfaces:
        config:
           - ipv4:
              - address: 192.168.13.1/24
             name: Ethernet3
        state: replaced
