---

- hosts: all
  
  tasks:
  
    - name: CONVERT TO LAYER3 ROUTED PORT
      eos_config:
        lines:
          - no switchport
          - ip routing
        parents: "{{ item }}"
      with_items:
        - "interface Ethernet1"
        - "interface Ethernet2"
        - "interface Ethernet3"
        - "interface Ethernet4"
        - "interface Ethernet5"
    
    - name: MERGE INTERFACES ETHERNET 1 AND 2
      eos_lag_interfaces:
        config:
          - name: Port-Channel1
            members:
              - member: Ethernet1
                mode: active
              - member: Ethernet2
                mode: active
        state: replaced
        
  roles:
    - eos_l3_interfaces
    - eos_ospf
    - eos_bgp
