ospf:
  - networks:
      - 192.168.13.1/24
      - 192.168.12.1/24
      - 192.168.13.1/24
      - 150.1.150.1/24
      - 1.1.1.1/32
    process_id: 1
    router_id: 1.1.1.1
    area: 0

bgp:
  - asn: 65535
    router_id: 1.1.1.1
    neighbors: 
      - neighbor: 150.1.150.1
        description: EBGP_PEER_ISP
        remote_as: 150
    networks:
      - prefix:
          - 1.1.1.1
        mask_length: 32


l2_interfaces:
  - interface_type: Ethernet
    interface_id: 1
    description: PORT-CHANNEL INTERFACE TO ARISTA-SW2
  - interface_type: Ethernet
    interface_id: 2
    description: PORT-CHANNEL INTERFACE TO ARISTA-SW2

l3_interfaces:
  - interface_type: Loopback
    interface_id: 0
    description: LOOPBACK INTERFACE
    ip_address: 1.1.1.1
    prefix: 32
  - interface_type: Ethernet
    interface_id: 3
    description: INTERFACE TO CUMULUS-SW1
    ip_address: 192.168.13.1
    prefix: 24
  - interface_type: Ethernet
    interface_id: 4
    description: INTERFACE TO CUMULUS-SW2
    ip_address: 192.168.14.1
    prefix: 24
  - interface_type: Ethernet
    interface_id: 5
    description: INTERFACE TO ISP
    ip_address: 150.1.150.1
    prefix: 24
  - interface_type: Port-Channel
    interface_id: 1
    description: INTERFACE TO CUMULUS-SW2
    ip_address: 192.168.12.1
    prefix: 24
    
management_interface:
  - interface_type: Management
    interface_id: 1
    description: MANAGEMENT INTERFACE
    
all_interfaces:
  - interface_type: Ethernet
    interface_id: 1
    description: PORT-CHANNEL INTERFACE TO ARISTA-SW2
  - interface_type: Ethernet
    interface_id: 2
    description: PORT-CHANNEL INTERFACE TO ARISTA-SW2
  - interface_type: Loopback
    interface_id: 0
    description: LOOPBACK INTERFACE
    ip_address: 1.1.1.1
    prefix: 32
  - interface_type: Ethernet
    interface_id: 3
    description: INTERFACE TO CUMULUS-SW1
    ip_address: 192.168.13.1
    prefix: 24
  - interface_type: Ethernet
    interface_id: 4
    description: INTERFACE TO CUMULUS-SW2
    ip_address: 192.168.14.1
    prefix: 24
  - interface_type: Ethernet
    interface_id: 5
    description: INTERFACE TO ISP
    ip_address: 150.1.150.1
    prefix: 24
  - interface_type: Port-Channel
    interface_id: 1
    description: INTERFACE TO CUMULUS-SW2
    ip_address: 192.168.12.1
    prefix: 24
  - interface_type: Management
    interface_id: 1
    description: MANAGEMENT INTERFACE