ospf_networks:
      - 192.168.12.2/24
      - 192.168.23.2/24
      - 192.168.24.2/24
      - 150.2.150.2/24
      - 2.2.2.2/32
ospf_process_id: 1
ospf_router_id: 2.2.2.2
ospf_area: 0

bgp_asn: 65535
bgp_router_id: 2.2.2.2
bgp_neighbors:
  - neighbor: 150.2.150.100
    description: EBGP_PEER_ISP
    remote_as: 150
bgp_networks:
    - prefix: 2.2.2.2
      mask_length: 32

l3_interfaces:
  - interface_type: Loopback
    interface_id: 0
    description: LOOPBACK INTERFACE
    ip_address: 2.2.2.2
    prefix: 32
  - interface_type: Ethernet
    interface_id: 3
    description: INTERFACE TO CUMULUS-SW2
    ip_address: 192.168.24.2
    prefix: 24
  - interface_type: Ethernet
    interface_id: 4
    description: INTERFACE TO CUMULUS-SW1
    ip_address: 192.168.23.2
    prefix: 24
  - interface_type: Ethernet
    interface_id: 5
    description: INTERFACE TO ISP
    ip_address: 150.2.150.2
    prefix: 24
  - interface_type: Port-Channel
    interface_id: 1
    description: INTERFACE TO CUMULUS-SW1
    ip_address: 192.168.12.2
    prefix: 24
    
management_interface:
  - interface_type: Management
    interface_id: 1
    description: MANAGEMENT INTERFACE
    
all_interfaces:
  - interface_type: Ethernet
    interface_id: 1
    description: PORT-CHANNEL INTERFACE TO ARISTA-SW1
  - interface_type: Ethernet
    interface_id: 2
    description: PORT-CHANNEL INTERFACE TO ARISTA-SW1
  - interface_type: Loopback
    interface_id: 0
    description: LOOPBACK INTERFACE
    ip_address: 2.2.2.2
    prefix: 32
  - interface_type: Ethernet
    interface_id: 3
    description: INTERFACE TO CUMULUS-SW2
    ip_address: 192.168.24.2
    prefix: 24
  - interface_type: Ethernet
    interface_id: 4
    description: INTERFACE TO CUMULUS-SW1
    ip_address: 192.168.23.2
    prefix: 24
  - interface_type: Ethernet
    interface_id: 5
    description: INTERFACE TO ISP
    ip_address: 150.2.150.2
    prefix: 24
  - interface_type: Port-Channel
    interface_id: 1
    description: INTERFACE TO CUMULUS-SW1
    ip_address: 192.168.12.2
    prefix: 24
  - interface_type: Management
    interface_id: 1
    description: MANAGEMENT INTERFACE
